### get all workouts from a user
GET http://127.0.0.1:3003/api/v1/workouts/alyssia1

### get one workout from a user
GET http://127.0.0.1:3003/api/v1/workouts/taimur1/0

### get list of users from search
GET http://127.0.0.1:3003/api/v1/users/find/a

### get all users
GET http://127.0.0.1:3003/api/v1/users

### follow a user
PATCH http://127.0.0.1:3003/api/v1/users/follow/taimur1/alyssia1

### unfollow a user
PATCH http://127.0.0.1:3003/api/v1/users/unfollow/v/b

### remove a workout from a user
DELETE http://127.0.0.1:3003/api/v1/workouts/taimur1/0


### get list of users a user is following
GET http://127.0.0.1:3003/api/v1/users/following/taimur1

### remove user
DELETE http://127.0.0.1:3003/api/v1/users/c

### create user
POST http://127.0.0.1:3003/api/v1/users
Content-Type: application/json

{
    "username": "shomari1",
    "password": "thompson1"
}

### login
POST http://127.0.0.1:3000/api/v1/users/login
Content-Type: application/json

{
    "username": "taimur1",
    "password": "tawil1"
}

### add workout
POST http://127.0.0.1:3003/api/v1/workouts/alyssia1
Content-Type: application/json

{
    
    "name": "crunches",
    "weight": 30,
    "reps": 10,
    "date": "2020-01-01"
}
### remove a workoutd
DELETE http://127.0.0.1:3003/api/v1/workouts/taimur/2

### seed database
POST http://127.0.0.1:3000/api/v1/users/seed

GET http://127.0.0.1:3003/api/v1/users/find/a
